version: '3'

services:
  db:
    image: postgres:9.6
    volumes:
    - postgres-data:/var/lib/postgresql/data
    env_file: .env
  backend:
    build:
      context: ./backend
    command: ./wait-for-it.sh db:5432 -- pipenv run ./sample/manage.py runserver 0.0.0.0:8000
    env_file: .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_USER}
    expose:
    - "8000"
    ports:
    - "8000:8000"
    volumes:
    - ./backend:/app
    depends_on:
    - db
  frontend:
    build:
      context: ./frontend
    command: bash -c "npm run dev"
    volumes:
    - ./frontend:/app
    expose:
    - "3000"
    ports:
    - "3000:3000"
    depends_on:
    - backend
  nginx:
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
    - ./config/nginx:/etc/nginx/conf.d
    depends_on:
    - backend
    - frontend

volumes:
  postgres-data:
    driver: local
